language: python
dist: trusty
python:
  - "3.5"
  - "3.6"
install: "pip install -e .[test]"
services: mongodb
script:
  - coverage run --source=app setup.py test
after_success:
  coveralls
env:
  - MONGO_URI=mongodb://127.0.0.1:27017/ MONGO_DB=aiohttp_sample APP_ENV=travis
